input.onButtonPressed(Button.A, function () {
    game.gameOver()
})
input.onGesture(Gesture.Shake, function () {
    music.playTone(494, music.beat(BeatFraction.Whole))
    music.playTone(262, music.beat(BeatFraction.Whole))
    music.playMelody("C D E F G A B C5 ", 120)
    music.playTone(349, music.beat(BeatFraction.Whole))
    music.playTone(370, music.beat(BeatFraction.Whole))
    music.playMelody("C D C5 C D C5 C D ", 120)
    music.playMelody("C D E D C D E D ", 120)
    music.playTone(587, music.beat(BeatFraction.Breve))
    if (Math.randomBoolean()) {
        game.setScore(1)
        basic.showString("1")
        music.playTone(247, music.beat(BeatFraction.Whole))
        music.playTone(139, music.beat(BeatFraction.Whole))
        music.playTone(277, music.beat(BeatFraction.Whole))
    } else {
        game.setScore(2)
        basic.showString("2")
        music.playTone(311, music.beat(BeatFraction.Whole))
        basic.pause(delay)
        music.playTone(311, music.beat(BeatFraction.Whole))
        music.playTone(659, music.beat(BeatFraction.Whole))
        music.playTone(698, music.beat(BeatFraction.Whole))
        music.playTone(523, music.beat(BeatFraction.Whole))
        music.playTone(880, music.beat(BeatFraction.Whole))
        music.playTone(988, music.beat(BeatFraction.Whole))
        music.playTone(932, music.beat(BeatFraction.Whole))
        music.playTone(740, music.beat(BeatFraction.Whole))
        music.playTone(554, music.beat(BeatFraction.Whole))
        music.playTone(131, music.beat(BeatFraction.Breve))
        music.playTone(131, music.beat(BeatFraction.Breve))
        music.playTone(587, music.beat(BeatFraction.Whole))
        music.playSoundEffect(music.createSoundEffect(WaveShape.Noise, 3295, 4864, 185, 255, 9999, SoundExpressionEffect.Tremolo, InterpolationCurve.Linear), SoundExpressionPlayMode.UntilDone)
        music.playSoundEffect(music.createSoundEffect(WaveShape.Sawtooth, 3758, 4828, 255, 255, 9999, SoundExpressionEffect.Tremolo, InterpolationCurve.Linear), SoundExpressionPlayMode.UntilDone)
        basic.showString("... Two very boring minuets later...")
        basic.pause(5000)
        music.playMelody("C5 C C C C C C D ", 20)
    }
})
let delay = 0
delay = 20
